//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionStock
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StockContainer : DbContext
    {
        public StockContainer()
            : base("name=StockContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BonsEntree> BonsEntrees { get; set; }
        public virtual DbSet<BonsSortie> BonsSorties { get; set; }
        public virtual DbSet<DetailBonSortieSet> DetailBonSortieSets { get; set; }
        public virtual DbSet<ProduitSet> ProduitSets { get; set; }
        public virtual DbSet<Recette> Recettes { get; set; }
        public virtual DbSet<RecetteProduit> RecetteProduits { get; set; }
    }
}
